const data3 = [
  {
    video: require('../videos/reels1.mp4'),
    image: require('../images/profil.jpg'),
    user: 'David',
    explanation: 'The memory..',
    likes: 852,
    comment: '35',
    isLike: false,
    follow: true,
  },
  {
    video: require('../videos/reels2.mp4'),
    image: require('../images/profil5.jpg'),
    user: 'Steve',
    explanation: 'I love my friends so much <3',
    likes: 25,
    comment: '14',
    isLike: false,
    follow: true,
  },
  {
    video: require('../videos/reels3.mp4'),
    image: require('../images/cat.jpg'),
    user: 'Jhon',
    explanation: 'Good morning',
    comment: 5,
    likes: 134,
    isLike: false,
    follow: true,
  },
  {
    video: require('../videos/reels4.mp4'),
    image: require('../images/ezgiceylan.jpeg'),
    user: 'Julia',
    explanation: 'a great weekend!',
    likes: 184,
    comment: '3',
    isLike: false,
    follow: true,
  },
  {
    video: require('../videos/reels5.mp4'),
    image: require('../images/profil6.jpg'),
    user: 'Finch',
    explanation: 'New phone',
    comment: 55,
    likes: 184,
    isLike: false,
    follow: true,
  },
  {
    video: require('../videos/reels6.mp4'),
    image: require('../images/profil3.jpg'),
    user: 'Jack',
    explanation: 'this vr is awesome dude..',
    likes: 124,
    comment: '96',
    isLike: false,
    follow: true,
  },
];
export default data3;
